// Vendored from github.com/NVIDIA/OpenShell/proto/datamodel.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: openshell/datamodel.proto

package openshell

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkPolicy_Action int32

const (
	NetworkPolicy_ALLOW NetworkPolicy_Action = 0
	NetworkPolicy_DENY  NetworkPolicy_Action = 1
)

// Enum value maps for NetworkPolicy_Action.
var (
	NetworkPolicy_Action_name = map[int32]string{
		0: "ALLOW",
		1: "DENY",
	}
	NetworkPolicy_Action_value = map[string]int32{
		"ALLOW": 0,
		"DENY":  1,
	}
)

func (x NetworkPolicy_Action) Enum() *NetworkPolicy_Action {
	p := new(NetworkPolicy_Action)
	*p = x
	return p
}

func (x NetworkPolicy_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkPolicy_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_openshell_datamodel_proto_enumTypes[0].Descriptor()
}

func (NetworkPolicy_Action) Type() protoreflect.EnumType {
	return &file_openshell_datamodel_proto_enumTypes[0]
}

func (x NetworkPolicy_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkPolicy_Action.Descriptor instead.
func (NetworkPolicy_Action) EnumDescriptor() ([]byte, []int) {
	return file_openshell_datamodel_proto_rawDescGZIP(), []int{3, 0}
}

type SandboxStatus_Phase int32

const (
	SandboxStatus_UNKNOWN SandboxStatus_Phase = 0
	SandboxStatus_PENDING SandboxStatus_Phase = 1
	SandboxStatus_RUNNING SandboxStatus_Phase = 2
	SandboxStatus_STOPPED SandboxStatus_Phase = 3
	SandboxStatus_FAILED  SandboxStatus_Phase = 4
)

// Enum value maps for SandboxStatus_Phase.
var (
	SandboxStatus_Phase_name = map[int32]string{
		0: "UNKNOWN",
		1: "PENDING",
		2: "RUNNING",
		3: "STOPPED",
		4: "FAILED",
	}
	SandboxStatus_Phase_value = map[string]int32{
		"UNKNOWN": 0,
		"PENDING": 1,
		"RUNNING": 2,
		"STOPPED": 3,
		"FAILED":  4,
	}
)

func (x SandboxStatus_Phase) Enum() *SandboxStatus_Phase {
	p := new(SandboxStatus_Phase)
	*p = x
	return p
}

func (x SandboxStatus_Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SandboxStatus_Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_openshell_datamodel_proto_enumTypes[1].Descriptor()
}

func (SandboxStatus_Phase) Type() protoreflect.EnumType {
	return &file_openshell_datamodel_proto_enumTypes[1]
}

func (x SandboxStatus_Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SandboxStatus_Phase.Descriptor instead.
func (SandboxStatus_Phase) EnumDescriptor() ([]byte, []int) {
	return file_openshell_datamodel_proto_rawDescGZIP(), []int{6, 0}
}

type SandboxSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Policy        *SandboxPolicy         `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	Env           map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Workspace     string                 `protobuf:"bytes,4,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxSpec) Reset() {
	*x = SandboxSpec{}
	mi := &file_openshell_datamodel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxSpec) ProtoMessage() {}

func (x *SandboxSpec) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_datamodel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxSpec.ProtoReflect.Descriptor instead.
func (*SandboxSpec) Descriptor() ([]byte, []int) {
	return file_openshell_datamodel_proto_rawDescGZIP(), []int{0}
}

func (x *SandboxSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *SandboxSpec) GetPolicy() *SandboxPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *SandboxSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *SandboxSpec) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type SandboxPolicy struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Filesystem      *FilesystemPolicy      `protobuf:"bytes,1,opt,name=filesystem,proto3" json:"filesystem,omitempty"`
	NetworkPolicies []*NetworkPolicy       `protobuf:"bytes,2,rep,name=network_policies,json=networkPolicies,proto3" json:"network_policies,omitempty"`
	Inference       *InferencePolicy       `protobuf:"bytes,3,opt,name=inference,proto3" json:"inference,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SandboxPolicy) Reset() {
	*x = SandboxPolicy{}
	mi := &file_openshell_datamodel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxPolicy) ProtoMessage() {}

func (x *SandboxPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_datamodel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxPolicy.ProtoReflect.Descriptor instead.
func (*SandboxPolicy) Descriptor() ([]byte, []int) {
	return file_openshell_datamodel_proto_rawDescGZIP(), []int{1}
}

func (x *SandboxPolicy) GetFilesystem() *FilesystemPolicy {
	if x != nil {
		return x.Filesystem
	}
	return nil
}

func (x *SandboxPolicy) GetNetworkPolicies() []*NetworkPolicy {
	if x != nil {
		return x.NetworkPolicies
	}
	return nil
}

func (x *SandboxPolicy) GetInference() *InferencePolicy {
	if x != nil {
		return x.Inference
	}
	return nil
}

type FilesystemPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReadOnly      []string               `protobuf:"bytes,1,rep,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	ReadWrite     []string               `protobuf:"bytes,2,rep,name=read_write,json=readWrite,proto3" json:"read_write,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesystemPolicy) Reset() {
	*x = FilesystemPolicy{}
	mi := &file_openshell_datamodel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesystemPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemPolicy) ProtoMessage() {}

func (x *FilesystemPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_datamodel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesystemPolicy.ProtoReflect.Descriptor instead.
func (*FilesystemPolicy) Descriptor() ([]byte, []int) {
	return file_openshell_datamodel_proto_rawDescGZIP(), []int{2}
}

func (x *FilesystemPolicy) GetReadOnly() []string {
	if x != nil {
		return x.ReadOnly
	}
	return nil
}

func (x *FilesystemPolicy) GetReadWrite() []string {
	if x != nil {
		return x.ReadWrite
	}
	return nil
}

type NetworkPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Action        NetworkPolicy_Action   `protobuf:"varint,2,opt,name=action,proto3,enum=openshell.NetworkPolicy_Action" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPolicy) Reset() {
	*x = NetworkPolicy{}
	mi := &file_openshell_datamodel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicy) ProtoMessage() {}

func (x *NetworkPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_datamodel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicy.ProtoReflect.Descriptor instead.
func (*NetworkPolicy) Descriptor() ([]byte, []int) {
	return file_openshell_datamodel_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkPolicy) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *NetworkPolicy) GetAction() NetworkPolicy_Action {
	if x != nil {
		return x.Action
	}
	return NetworkPolicy_ALLOW
}

type InferencePolicy struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoutingEnabled bool                   `protobuf:"varint,1,opt,name=routing_enabled,json=routingEnabled,proto3" json:"routing_enabled,omitempty"`
	Provider       string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InferencePolicy) Reset() {
	*x = InferencePolicy{}
	mi := &file_openshell_datamodel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferencePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferencePolicy) ProtoMessage() {}

func (x *InferencePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_datamodel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferencePolicy.ProtoReflect.Descriptor instead.
func (*InferencePolicy) Descriptor() ([]byte, []int) {
	return file_openshell_datamodel_proto_rawDescGZIP(), []int{4}
}

func (x *InferencePolicy) GetRoutingEnabled() bool {
	if x != nil {
		return x.RoutingEnabled
	}
	return false
}

func (x *InferencePolicy) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type Sandbox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SandboxId     string                 `protobuf:"bytes,2,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Spec          *SandboxSpec           `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *SandboxStatus         `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sandbox) Reset() {
	*x = Sandbox{}
	mi := &file_openshell_datamodel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sandbox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sandbox) ProtoMessage() {}

func (x *Sandbox) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_datamodel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sandbox.ProtoReflect.Descriptor instead.
func (*Sandbox) Descriptor() ([]byte, []int) {
	return file_openshell_datamodel_proto_rawDescGZIP(), []int{5}
}

func (x *Sandbox) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Sandbox) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *Sandbox) GetSpec() *SandboxSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Sandbox) GetStatus() *SandboxStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type SandboxStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         SandboxStatus_Phase    `protobuf:"varint,1,opt,name=phase,proto3,enum=openshell.SandboxStatus_Phase" json:"phase,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxStatus) Reset() {
	*x = SandboxStatus{}
	mi := &file_openshell_datamodel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxStatus) ProtoMessage() {}

func (x *SandboxStatus) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_datamodel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxStatus.ProtoReflect.Descriptor instead.
func (*SandboxStatus) Descriptor() ([]byte, []int) {
	return file_openshell_datamodel_proto_rawDescGZIP(), []int{6}
}

func (x *SandboxStatus) GetPhase() SandboxStatus_Phase {
	if x != nil {
		return x.Phase
	}
	return SandboxStatus_UNKNOWN
}

func (x *SandboxStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_openshell_datamodel_proto protoreflect.FileDescriptor

const file_openshell_datamodel_proto_rawDesc = "" +
	"\n" +
	"\x19openshell/datamodel.proto\x12\topenshell\"\xde\x01\n" +
	"\vSandboxSpec\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x120\n" +
	"\x06policy\x18\x02 \x01(\v2\x18.openshell.SandboxPolicyR\x06policy\x121\n" +
	"\x03env\x18\x03 \x03(\v2\x1f.openshell.SandboxSpec.EnvEntryR\x03env\x12\x1c\n" +
	"\tworkspace\x18\x04 \x01(\tR\tworkspace\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcb\x01\n" +
	"\rSandboxPolicy\x12;\n" +
	"\n" +
	"filesystem\x18\x01 \x01(\v2\x1b.openshell.FilesystemPolicyR\n" +
	"filesystem\x12C\n" +
	"\x10network_policies\x18\x02 \x03(\v2\x18.openshell.NetworkPolicyR\x0fnetworkPolicies\x128\n" +
	"\tinference\x18\x03 \x01(\v2\x1a.openshell.InferencePolicyR\tinference\"N\n" +
	"\x10FilesystemPolicy\x12\x1b\n" +
	"\tread_only\x18\x01 \x03(\tR\breadOnly\x12\x1d\n" +
	"\n" +
	"read_write\x18\x02 \x03(\tR\treadWrite\"{\n" +
	"\rNetworkPolicy\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\x127\n" +
	"\x06action\x18\x02 \x01(\x0e2\x1f.openshell.NetworkPolicy.ActionR\x06action\"\x1d\n" +
	"\x06Action\x12\t\n" +
	"\x05ALLOW\x10\x00\x12\b\n" +
	"\x04DENY\x10\x01\"V\n" +
	"\x0fInferencePolicy\x12'\n" +
	"\x0frouting_enabled\x18\x01 \x01(\bR\x0eroutingEnabled\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\"\x9a\x01\n" +
	"\aSandbox\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x02 \x01(\tR\tsandboxId\x12*\n" +
	"\x04spec\x18\x03 \x01(\v2\x16.openshell.SandboxSpecR\x04spec\x120\n" +
	"\x06status\x18\x04 \x01(\v2\x18.openshell.SandboxStatusR\x06status\"\xa8\x01\n" +
	"\rSandboxStatus\x124\n" +
	"\x05phase\x18\x01 \x01(\x0e2\x1e.openshell.SandboxStatus.PhaseR\x05phase\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"G\n" +
	"\x05Phase\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\v\n" +
	"\aSTOPPED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04B-Z+github.com/NVIDIA/OpenShell/proto/openshellb\x06proto3"

var (
	file_openshell_datamodel_proto_rawDescOnce sync.Once
	file_openshell_datamodel_proto_rawDescData []byte
)

func file_openshell_datamodel_proto_rawDescGZIP() []byte {
	file_openshell_datamodel_proto_rawDescOnce.Do(func() {
		file_openshell_datamodel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openshell_datamodel_proto_rawDesc), len(file_openshell_datamodel_proto_rawDesc)))
	})
	return file_openshell_datamodel_proto_rawDescData
}

var file_openshell_datamodel_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_openshell_datamodel_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_openshell_datamodel_proto_goTypes = []any{
	(NetworkPolicy_Action)(0), // 0: openshell.NetworkPolicy.Action
	(SandboxStatus_Phase)(0),  // 1: openshell.SandboxStatus.Phase
	(*SandboxSpec)(nil),       // 2: openshell.SandboxSpec
	(*SandboxPolicy)(nil),     // 3: openshell.SandboxPolicy
	(*FilesystemPolicy)(nil),  // 4: openshell.FilesystemPolicy
	(*NetworkPolicy)(nil),     // 5: openshell.NetworkPolicy
	(*InferencePolicy)(nil),   // 6: openshell.InferencePolicy
	(*Sandbox)(nil),           // 7: openshell.Sandbox
	(*SandboxStatus)(nil),     // 8: openshell.SandboxStatus
	nil,                       // 9: openshell.SandboxSpec.EnvEntry
}
var file_openshell_datamodel_proto_depIdxs = []int32{
	3, // 0: openshell.SandboxSpec.policy:type_name -> openshell.SandboxPolicy
	9, // 1: openshell.SandboxSpec.env:type_name -> openshell.SandboxSpec.EnvEntry
	4, // 2: openshell.SandboxPolicy.filesystem:type_name -> openshell.FilesystemPolicy
	5, // 3: openshell.SandboxPolicy.network_policies:type_name -> openshell.NetworkPolicy
	6, // 4: openshell.SandboxPolicy.inference:type_name -> openshell.InferencePolicy
	0, // 5: openshell.NetworkPolicy.action:type_name -> openshell.NetworkPolicy.Action
	2, // 6: openshell.Sandbox.spec:type_name -> openshell.SandboxSpec
	8, // 7: openshell.Sandbox.status:type_name -> openshell.SandboxStatus
	1, // 8: openshell.SandboxStatus.phase:type_name -> openshell.SandboxStatus.Phase
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_openshell_datamodel_proto_init() }
func file_openshell_datamodel_proto_init() {
	if File_openshell_datamodel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openshell_datamodel_proto_rawDesc), len(file_openshell_datamodel_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openshell_datamodel_proto_goTypes,
		DependencyIndexes: file_openshell_datamodel_proto_depIdxs,
		EnumInfos:         file_openshell_datamodel_proto_enumTypes,
		MessageInfos:      file_openshell_datamodel_proto_msgTypes,
	}.Build()
	File_openshell_datamodel_proto = out.File
	file_openshell_datamodel_proto_goTypes = nil
	file_openshell_datamodel_proto_depIdxs = nil
}
