// Vendored from github.com/NVIDIA/OpenShell/proto/openshell.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: openshell/openshell.proto

package openshell

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthResponse_ServingStatus int32

const (
	HealthResponse_UNKNOWN     HealthResponse_ServingStatus = 0
	HealthResponse_SERVING     HealthResponse_ServingStatus = 1
	HealthResponse_NOT_SERVING HealthResponse_ServingStatus = 2
)

// Enum value maps for HealthResponse_ServingStatus.
var (
	HealthResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthResponse_ServingStatus) Enum() *HealthResponse_ServingStatus {
	p := new(HealthResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_openshell_openshell_proto_enumTypes[0].Descriptor()
}

func (HealthResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_openshell_openshell_proto_enumTypes[0]
}

func (x HealthResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthResponse_ServingStatus.Descriptor instead.
func (HealthResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_openshell_openshell_proto_rawDescGZIP(), []int{1, 0}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_openshell_openshell_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_openshell_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_openshell_openshell_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Status        HealthResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=openshell.HealthResponse_ServingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_openshell_openshell_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_openshell_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_openshell_openshell_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() HealthResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthResponse_UNKNOWN
}

var File_openshell_openshell_proto protoreflect.FileDescriptor

const file_openshell_openshell_proto_rawDesc = "" +
	"\n" +
	"\x19openshell/openshell.proto\x12\topenshell\x1a\x17openshell/sandbox.proto\"\x0f\n" +
	"\rHealthRequest\"\x8d\x01\n" +
	"\x0eHealthResponse\x12?\n" +
	"\x06status\x18\x01 \x01(\x0e2'.openshell.HealthResponse.ServingStatusR\x06status\":\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x022\x8a\x03\n" +
	"\tOpenShell\x12R\n" +
	"\rCreateSandbox\x12\x1f.openshell.CreateSandboxRequest\x1a .openshell.CreateSandboxResponse\x12R\n" +
	"\rDeleteSandbox\x12\x1f.openshell.DeleteSandboxRequest\x1a .openshell.DeleteSandboxResponse\x12I\n" +
	"\n" +
	"GetSandbox\x12\x1c.openshell.GetSandboxRequest\x1a\x1d.openshell.GetSandboxResponse\x12K\n" +
	"\vExecSandbox\x12\x1d.openshell.ExecSandboxRequest\x1a\x1b.openshell.ExecSandboxEvent0\x01\x12=\n" +
	"\x06Health\x12\x18.openshell.HealthRequest\x1a\x19.openshell.HealthResponseB-Z+github.com/NVIDIA/OpenShell/proto/openshellb\x06proto3"

var (
	file_openshell_openshell_proto_rawDescOnce sync.Once
	file_openshell_openshell_proto_rawDescData []byte
)

func file_openshell_openshell_proto_rawDescGZIP() []byte {
	file_openshell_openshell_proto_rawDescOnce.Do(func() {
		file_openshell_openshell_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openshell_openshell_proto_rawDesc), len(file_openshell_openshell_proto_rawDesc)))
	})
	return file_openshell_openshell_proto_rawDescData
}

var file_openshell_openshell_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_openshell_openshell_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_openshell_openshell_proto_goTypes = []any{
	(HealthResponse_ServingStatus)(0), // 0: openshell.HealthResponse.ServingStatus
	(*HealthRequest)(nil),             // 1: openshell.HealthRequest
	(*HealthResponse)(nil),            // 2: openshell.HealthResponse
	(*CreateSandboxRequest)(nil),      // 3: openshell.CreateSandboxRequest
	(*DeleteSandboxRequest)(nil),      // 4: openshell.DeleteSandboxRequest
	(*GetSandboxRequest)(nil),         // 5: openshell.GetSandboxRequest
	(*ExecSandboxRequest)(nil),        // 6: openshell.ExecSandboxRequest
	(*CreateSandboxResponse)(nil),     // 7: openshell.CreateSandboxResponse
	(*DeleteSandboxResponse)(nil),     // 8: openshell.DeleteSandboxResponse
	(*GetSandboxResponse)(nil),        // 9: openshell.GetSandboxResponse
	(*ExecSandboxEvent)(nil),          // 10: openshell.ExecSandboxEvent
}
var file_openshell_openshell_proto_depIdxs = []int32{
	0,  // 0: openshell.HealthResponse.status:type_name -> openshell.HealthResponse.ServingStatus
	3,  // 1: openshell.OpenShell.CreateSandbox:input_type -> openshell.CreateSandboxRequest
	4,  // 2: openshell.OpenShell.DeleteSandbox:input_type -> openshell.DeleteSandboxRequest
	5,  // 3: openshell.OpenShell.GetSandbox:input_type -> openshell.GetSandboxRequest
	6,  // 4: openshell.OpenShell.ExecSandbox:input_type -> openshell.ExecSandboxRequest
	1,  // 5: openshell.OpenShell.Health:input_type -> openshell.HealthRequest
	7,  // 6: openshell.OpenShell.CreateSandbox:output_type -> openshell.CreateSandboxResponse
	8,  // 7: openshell.OpenShell.DeleteSandbox:output_type -> openshell.DeleteSandboxResponse
	9,  // 8: openshell.OpenShell.GetSandbox:output_type -> openshell.GetSandboxResponse
	10, // 9: openshell.OpenShell.ExecSandbox:output_type -> openshell.ExecSandboxEvent
	2,  // 10: openshell.OpenShell.Health:output_type -> openshell.HealthResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_openshell_openshell_proto_init() }
func file_openshell_openshell_proto_init() {
	if File_openshell_openshell_proto != nil {
		return
	}
	file_openshell_sandbox_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openshell_openshell_proto_rawDesc), len(file_openshell_openshell_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_openshell_openshell_proto_goTypes,
		DependencyIndexes: file_openshell_openshell_proto_depIdxs,
		EnumInfos:         file_openshell_openshell_proto_enumTypes,
		MessageInfos:      file_openshell_openshell_proto_msgTypes,
	}.Build()
	File_openshell_openshell_proto = out.File
	file_openshell_openshell_proto_goTypes = nil
	file_openshell_openshell_proto_depIdxs = nil
}
