// Vendored from github.com/NVIDIA/OpenShell/proto/sandbox.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: openshell/sandbox.proto

package openshell

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Spec          *SandboxSpec           `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSandboxRequest) Reset() {
	*x = CreateSandboxRequest{}
	mi := &file_openshell_sandbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxRequest) ProtoMessage() {}

func (x *CreateSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_sandbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxRequest.ProtoReflect.Descriptor instead.
func (*CreateSandboxRequest) Descriptor() ([]byte, []int) {
	return file_openshell_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSandboxRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSandboxRequest) GetSpec() *SandboxSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type CreateSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandbox       *Sandbox               `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSandboxResponse) Reset() {
	*x = CreateSandboxResponse{}
	mi := &file_openshell_sandbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxResponse) ProtoMessage() {}

func (x *CreateSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_sandbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxResponse.ProtoReflect.Descriptor instead.
func (*CreateSandboxResponse) Descriptor() ([]byte, []int) {
	return file_openshell_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSandboxResponse) GetSandbox() *Sandbox {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

type DeleteSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSandboxRequest) Reset() {
	*x = DeleteSandboxRequest{}
	mi := &file_openshell_sandbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSandboxRequest) ProtoMessage() {}

func (x *DeleteSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_sandbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSandboxRequest.ProtoReflect.Descriptor instead.
func (*DeleteSandboxRequest) Descriptor() ([]byte, []int) {
	return file_openshell_sandbox_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteSandboxRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSandboxResponse) Reset() {
	*x = DeleteSandboxResponse{}
	mi := &file_openshell_sandbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSandboxResponse) ProtoMessage() {}

func (x *DeleteSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_sandbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSandboxResponse.ProtoReflect.Descriptor instead.
func (*DeleteSandboxResponse) Descriptor() ([]byte, []int) {
	return file_openshell_sandbox_proto_rawDescGZIP(), []int{3}
}

type GetSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxRequest) Reset() {
	*x = GetSandboxRequest{}
	mi := &file_openshell_sandbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxRequest) ProtoMessage() {}

func (x *GetSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_sandbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxRequest.ProtoReflect.Descriptor instead.
func (*GetSandboxRequest) Descriptor() ([]byte, []int) {
	return file_openshell_sandbox_proto_rawDescGZIP(), []int{4}
}

func (x *GetSandboxRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandbox       *Sandbox               `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxResponse) Reset() {
	*x = GetSandboxResponse{}
	mi := &file_openshell_sandbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxResponse) ProtoMessage() {}

func (x *GetSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_sandbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxResponse.ProtoReflect.Descriptor instead.
func (*GetSandboxResponse) Descriptor() ([]byte, []int) {
	return file_openshell_sandbox_proto_rawDescGZIP(), []int{5}
}

func (x *GetSandboxResponse) GetSandbox() *Sandbox {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

type ExecSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Command       []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	Env           map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkingDir    string                 `protobuf:"bytes,4,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecSandboxRequest) Reset() {
	*x = ExecSandboxRequest{}
	mi := &file_openshell_sandbox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecSandboxRequest) ProtoMessage() {}

func (x *ExecSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_sandbox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecSandboxRequest.ProtoReflect.Descriptor instead.
func (*ExecSandboxRequest) Descriptor() ([]byte, []int) {
	return file_openshell_sandbox_proto_rawDescGZIP(), []int{6}
}

func (x *ExecSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ExecSandboxRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ExecSandboxRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecSandboxRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

type ExecSandboxEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ExecSandboxEvent_Stdout
	//	*ExecSandboxEvent_Stderr
	//	*ExecSandboxEvent_Exit
	Event         isExecSandboxEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecSandboxEvent) Reset() {
	*x = ExecSandboxEvent{}
	mi := &file_openshell_sandbox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecSandboxEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecSandboxEvent) ProtoMessage() {}

func (x *ExecSandboxEvent) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_sandbox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecSandboxEvent.ProtoReflect.Descriptor instead.
func (*ExecSandboxEvent) Descriptor() ([]byte, []int) {
	return file_openshell_sandbox_proto_rawDescGZIP(), []int{7}
}

func (x *ExecSandboxEvent) GetEvent() isExecSandboxEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ExecSandboxEvent) GetStdout() *StdoutChunk {
	if x != nil {
		if x, ok := x.Event.(*ExecSandboxEvent_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ExecSandboxEvent) GetStderr() *StderrChunk {
	if x != nil {
		if x, ok := x.Event.(*ExecSandboxEvent_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ExecSandboxEvent) GetExit() *ExitStatus {
	if x != nil {
		if x, ok := x.Event.(*ExecSandboxEvent_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

type isExecSandboxEvent_Event interface {
	isExecSandboxEvent_Event()
}

type ExecSandboxEvent_Stdout struct {
	Stdout *StdoutChunk `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ExecSandboxEvent_Stderr struct {
	Stderr *StderrChunk `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type ExecSandboxEvent_Exit struct {
	Exit *ExitStatus `protobuf:"bytes,3,opt,name=exit,proto3,oneof"`
}

func (*ExecSandboxEvent_Stdout) isExecSandboxEvent_Event() {}

func (*ExecSandboxEvent_Stderr) isExecSandboxEvent_Event() {}

func (*ExecSandboxEvent_Exit) isExecSandboxEvent_Event() {}

type StdoutChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StdoutChunk) Reset() {
	*x = StdoutChunk{}
	mi := &file_openshell_sandbox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StdoutChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StdoutChunk) ProtoMessage() {}

func (x *StdoutChunk) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_sandbox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StdoutChunk.ProtoReflect.Descriptor instead.
func (*StdoutChunk) Descriptor() ([]byte, []int) {
	return file_openshell_sandbox_proto_rawDescGZIP(), []int{8}
}

func (x *StdoutChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type StderrChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StderrChunk) Reset() {
	*x = StderrChunk{}
	mi := &file_openshell_sandbox_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StderrChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StderrChunk) ProtoMessage() {}

func (x *StderrChunk) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_sandbox_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StderrChunk.ProtoReflect.Descriptor instead.
func (*StderrChunk) Descriptor() ([]byte, []int) {
	return file_openshell_sandbox_proto_rawDescGZIP(), []int{9}
}

func (x *StderrChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ExitStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitStatus) Reset() {
	*x = ExitStatus{}
	mi := &file_openshell_sandbox_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitStatus) ProtoMessage() {}

func (x *ExitStatus) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_sandbox_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitStatus.ProtoReflect.Descriptor instead.
func (*ExitStatus) Descriptor() ([]byte, []int) {
	return file_openshell_sandbox_proto_rawDescGZIP(), []int{10}
}

func (x *ExitStatus) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_openshell_sandbox_proto protoreflect.FileDescriptor

const file_openshell_sandbox_proto_rawDesc = "" +
	"\n" +
	"\x17openshell/sandbox.proto\x12\topenshell\x1a\x19openshell/datamodel.proto\"V\n" +
	"\x14CreateSandboxRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\x04spec\x18\x02 \x01(\v2\x16.openshell.SandboxSpecR\x04spec\"E\n" +
	"\x15CreateSandboxResponse\x12,\n" +
	"\asandbox\x18\x01 \x01(\v2\x12.openshell.SandboxR\asandbox\"*\n" +
	"\x14DeleteSandboxRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x17\n" +
	"\x15DeleteSandboxResponse\"'\n" +
	"\x11GetSandboxRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"B\n" +
	"\x12GetSandboxResponse\x12,\n" +
	"\asandbox\x18\x01 \x01(\v2\x12.openshell.SandboxR\asandbox\"\xe0\x01\n" +
	"\x12ExecSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x128\n" +
	"\x03env\x18\x03 \x03(\v2&.openshell.ExecSandboxRequest.EnvEntryR\x03env\x12\x1f\n" +
	"\vworking_dir\x18\x04 \x01(\tR\n" +
	"workingDir\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xac\x01\n" +
	"\x10ExecSandboxEvent\x120\n" +
	"\x06stdout\x18\x01 \x01(\v2\x16.openshell.StdoutChunkH\x00R\x06stdout\x120\n" +
	"\x06stderr\x18\x02 \x01(\v2\x16.openshell.StderrChunkH\x00R\x06stderr\x12+\n" +
	"\x04exit\x18\x03 \x01(\v2\x15.openshell.ExitStatusH\x00R\x04exitB\a\n" +
	"\x05event\"!\n" +
	"\vStdoutChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"!\n" +
	"\vStderrChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\" \n" +
	"\n" +
	"ExitStatus\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04codeB-Z+github.com/NVIDIA/OpenShell/proto/openshellb\x06proto3"

var (
	file_openshell_sandbox_proto_rawDescOnce sync.Once
	file_openshell_sandbox_proto_rawDescData []byte
)

func file_openshell_sandbox_proto_rawDescGZIP() []byte {
	file_openshell_sandbox_proto_rawDescOnce.Do(func() {
		file_openshell_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openshell_sandbox_proto_rawDesc), len(file_openshell_sandbox_proto_rawDesc)))
	})
	return file_openshell_sandbox_proto_rawDescData
}

var file_openshell_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_openshell_sandbox_proto_goTypes = []any{
	(*CreateSandboxRequest)(nil),  // 0: openshell.CreateSandboxRequest
	(*CreateSandboxResponse)(nil), // 1: openshell.CreateSandboxResponse
	(*DeleteSandboxRequest)(nil),  // 2: openshell.DeleteSandboxRequest
	(*DeleteSandboxResponse)(nil), // 3: openshell.DeleteSandboxResponse
	(*GetSandboxRequest)(nil),     // 4: openshell.GetSandboxRequest
	(*GetSandboxResponse)(nil),    // 5: openshell.GetSandboxResponse
	(*ExecSandboxRequest)(nil),    // 6: openshell.ExecSandboxRequest
	(*ExecSandboxEvent)(nil),      // 7: openshell.ExecSandboxEvent
	(*StdoutChunk)(nil),           // 8: openshell.StdoutChunk
	(*StderrChunk)(nil),           // 9: openshell.StderrChunk
	(*ExitStatus)(nil),            // 10: openshell.ExitStatus
	nil,                           // 11: openshell.ExecSandboxRequest.EnvEntry
	(*SandboxSpec)(nil),           // 12: openshell.SandboxSpec
	(*Sandbox)(nil),               // 13: openshell.Sandbox
}
var file_openshell_sandbox_proto_depIdxs = []int32{
	12, // 0: openshell.CreateSandboxRequest.spec:type_name -> openshell.SandboxSpec
	13, // 1: openshell.CreateSandboxResponse.sandbox:type_name -> openshell.Sandbox
	13, // 2: openshell.GetSandboxResponse.sandbox:type_name -> openshell.Sandbox
	11, // 3: openshell.ExecSandboxRequest.env:type_name -> openshell.ExecSandboxRequest.EnvEntry
	8,  // 4: openshell.ExecSandboxEvent.stdout:type_name -> openshell.StdoutChunk
	9,  // 5: openshell.ExecSandboxEvent.stderr:type_name -> openshell.StderrChunk
	10, // 6: openshell.ExecSandboxEvent.exit:type_name -> openshell.ExitStatus
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_openshell_sandbox_proto_init() }
func file_openshell_sandbox_proto_init() {
	if File_openshell_sandbox_proto != nil {
		return
	}
	file_openshell_datamodel_proto_init()
	file_openshell_sandbox_proto_msgTypes[7].OneofWrappers = []any{
		(*ExecSandboxEvent_Stdout)(nil),
		(*ExecSandboxEvent_Stderr)(nil),
		(*ExecSandboxEvent_Exit)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openshell_sandbox_proto_rawDesc), len(file_openshell_sandbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openshell_sandbox_proto_goTypes,
		DependencyIndexes: file_openshell_sandbox_proto_depIdxs,
		MessageInfos:      file_openshell_sandbox_proto_msgTypes,
	}.Build()
	File_openshell_sandbox_proto = out.File
	file_openshell_sandbox_proto_goTypes = nil
	file_openshell_sandbox_proto_depIdxs = nil
}
